name: Static Analysis & MISRA Compliance

# Trigger this workflow on every 'push' or 'pull request' to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static_analisys:
    runs-on: ubuntu-latest

    steps:
    # --- CppCheck Steps ---
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run Cppcheck
      id: cppcheck_run
      run: |
        cppcheck --enable=all --std=c99 \
        --template=gcc \
        --error-exitcode=1 \
        --addon=misra \
        --inline-suppr \
        --suppress=misra-c2012-11.1 \
        --suppress=misra-c2012-1.1 \
        -D_POSIX_C_SOURCE=200809L \
        -I include/ \
        src/
    
    - name: Upload Cppcheck results artifact
      uses: actions/upload-artifact@v4
      with:
        name: cppcheck-results
        path: cppcheck_results.xml
